// Fallback Supabase client for browser if env vars are not yet injected
// Prefer using the autogenerated client in src/integrations/supabase/client,
// but this ensures the app runs even if Vite envs are momentarily unavailable.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";

const PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID || "pxvwgaqzlsqttcdlynxh";
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || `https://${PROJECT_ID}.supabase.co`;
// This is a public anon key; safe to expose in the browser. Prefer env, fallback to Cloud-provided value.
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4dndnYXF6bHNxdHRjZGx5bnhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwOTIyMTEsImV4cCI6MjA3NzY2ODIxMX0.5zLbXnMGiZBf08ViiWTM1pam1cfudfK8S5uVD4FNbhk";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
